### ISSUE TITLE
REST API: dc:type not included

### ISSUE THREAD

**Issue by jthomsen** [linkedtv/platform#18]
full annotation on the platform REST api does not return dc:type (DBPedia/Freebase) of entities, included in the uploaded (on the SVN) RDFs

Source: WP2 Telco 2013/10/01

**Comment by rtroncy** [comment]
Is this just something you forgot to add in the API? Note that in year 3, we will update this part in the annotation process where we are likely to return multiple rdf:type for the detected entities. This will reflect the great power of THD and other extractors that provide fine-grained types.

**Comment by dorotheatsatsou** [comment]
Probably forgotten, but now it is supported, quoting @alisarioglu (from 5/11/2013):

"you can get the value from dc:type from an annotation by adding the URL parameter _properties=hasBody.Type to the URL.

Here is an example, with normal view:
http://data.linkedtv.eu/annotation?_view=normal&hasBody=http://data.linkedtv.eu/entity/5dbdd085-7454-4556-8ea1-d41d4aa77235&_properties=hasBody.Type

To keep it work with the linked data api (Elda) I’ve to define a different short name for the dc:type.
For rdf:type short name is type.
For dc:type short name is Type (maybe something like dctype or dcType is better)."

However, problems still remain, will discuss it first on the WPs 2 and 5 mailing lists (has to do with supported serialization) and see if we should return to this issue or raise a separate one. 

Excellent enhancement to have all types of an entity returned as a collection of multiple rdf:type, would be much preferred.

**Comment by rtroncy** [comment]
Thanks Dorothea, I still have many more LinkedTV emails to read, but I'm getting there :-)
What is producing statements with dc:type ? It seems to me that rdf:type should always be used, in particular in the example you just pointed out.

**Comment by dorotheatsatsou** [comment]
Don't worry, I think this solution was not communicated publicly yet, I guess because of subsequent issues.
I agree that rdf:type should always be used. . 

Statements with dc:type are often fine-grained and are only returned in the annotation of text, denoting the type (in dbpedia, freebase and an unknown source, see problem below) of an entity extracted within a segment of the text. They are additional to rdf:type for the entity, which basically states that the entity in the body of the annotation is in fact a linkedtv:Entity and returns its nerd type. 

Example for the same annotation:
http://data.linkedtv.eu/annotation/c6628214-e227-4087-900d-08d21cd68686?_view=normal&_properties=hasBody.type   (rdf:type)
http://data.linkedtv.eu/annotation/c6628214-e227-4087-900d-08d21cd68686?_view=normal&_properties=hasBody.Type   (dc:type)

I can point to examples in the rdf files of the review videos if you'd like.

Now, a major problem in these statements is their serialization. Examples of dc:type returned as retrieved by Ali include:
dc:type "null"
dc:type "http://dbpedia.org/resource/Given_name" ;
dc:type "DBpedia:Currency;Freebase:/sports/sports_position,/finance/currency" ;
dc:type "organization" ;
dc:type "DBpedia:Event,Year" ;

Because of the different serializations, Ali could not parse dc:type, so for now only the string representation is returned through the &_properties=hasBody.Type option.

Ok, so I've just looked through the sources of the different serializations:
- Types of the form "DBpedia:Event,Year" and  "DBpedia:Currency;Freebase:/sports/sports_position,/finance/currency" are extracted by textrazor in the asr analysis (I am familiar with that, I have worked on them for the ICASSP paper). They have dc:source "textrazor" in the rdfs.
- dc:type of the form "http://dbpedia.org/resource/..." or http://dbpedia.org/ontology/..." have as dc:source "thd".
- Both textrazor and thd return dc:type "null".
- dc:type with no vocabulary reference like dc:type "organization" ; or dc:type "person" ; come from dc:source "semitags". Have not seen an instance where semitags returns null.

**Comment by rtroncy** [comment]
Thanks for digging into the issue. Now, I'm starting to put all the pieces together. What you're saying is that an entity detected in the transcript through the NERD platform will be:
- minted in the http://data.linkedtv.eu/entity/UUID namespace
- rdf:type linkedtv:Entity
- owl:sameAs dbpedia/freebase/etc. resources
- dc:type dbpedia-owl/freebase/etc. more fine-grained types
  This is the last statement which is controversial. I still wonder why we made this choice and I presume NERD/TV2RDF is responsible for this. I will discuss this issue with @jluisred .

Independently of the usage of rdf:type and dc:type, we need also to normalize those values.
- SemiTags ... why strings are returned instead of URI? [UEP ... what are your github ids to add you in this thread?]
- THD: why the hell you have http://dbpedia.org/resource/... returned as type and not only dbpedia-owl?
- We need to filter out the NULL obviously in the TV2RDF logic

**Comment by dorotheatsatsou** [comment]
Thanks for looking into this issue.

> > What you're saying is that an entity detected in the transcript through the NERD platform will be:
> > - minted in the http://data.linkedtv.eu/entity/UUID namespace
- Yes
  
  > > - rdf:type linkedtv:Entity
- Yes but also: rdf:type linkedtv:Entity, nerd:{something}
  
  > > - owl:sameAs dbpedia/freebase/etc. resources
- owl:sameAs wikipedia entries (from textrazor) or dbpedia resources (from thd and semitags). No freebase resource here. E.g. owl:sameAs http://nl.wikipedia.org/wiki/Parijs or owl:sameAs http://de.dbpedia.org/resource/Giacomo_Puccini
  
  > > - dc:type dbpedia-owl/freebase/etc. more fine-grained types This is the last statement which is controversial.
- Yes.

**Comment by rtroncy** [comment]
Good, we have well-captured the issue :-) Now, let's work on a solution :-)
Note that owl:sameAs a wikipedia resource is also something I think we should avoid (and instead normalize with a dbpedia URI which has a foaf:page a wikipedia resource)

**Comment by jthomsen** [comment]
OK, good discussion; so who is now in charge? guess it's @rtroncy, right? So, I assign to you; yoz may assign to somebody else again; we need the UEP github ids, true :-)

**Comment by rtroncy** [comment]
Nope, this is @jluisred !

**Comment by jthomsen** [comment]
ok, @jluisred is assigned ;-)

**Comment by dorotheatsatsou** [comment]
Thanks!

Note that I forgot:

> Independently of the usage of rdf:type and dc:type, we need also to normalize those values.

Yes.

> Note that owl:sameAs a wikipedia resource is also something I think we should avoid (and instead normalize with a dbpedia URI which has a foaf:page a wikipedia resource)

I agree.

**Comment by kliegr** [comment]
> - THD: why the hell you have http://dbpedia.org/resource/... returned as type and not only dbpedia-owl?

This is indeed a feature not a bug. It comes from the underlying LHD dataset, which tries to attach as precise types as possible. In almost all cases THD now (as of LHD 2.0 draft) returns also a more generic DBpedia Ontology type in addition to the specific "resource"  type, so you can discard the "resource" type if needs be.

**Comment by rtroncy** [comment]
This cannot be a feature, sorry. Let me explain:  http://dbpedia.org/resource/xxx is not a type. It is an instance, which has a rdf:type. You can GET the rdf:type of the resource by dereferencing the resource URI, but I'm asking why do you put this URI in the type field where clearly, this is NOT a type. Do you see my point @kliegr ?

**Comment by kliegr** [comment]
The types_filter parameter in the version 2 of the THD API allows to remove types from the dbpedia.org/resource namespace from the output. Also this version includes LHD 2.0, which increases the coverage of DBpedia Ontology types to 95%+ (for English). This should help to resolve this issue.

On a more theoretical level, we also had doubts on whether using DBpedia resource as a class is the correct modelling approach. This motivated our  work on LHD 2.0. However, there are others (<a href="http://link.springer.com/chapter/10.1007%2F978-3-642-35176-1_5">Gangemi et al. 2012</a>) doing the same.  Their Tipalo system  detects whether the entity should be represented as a class or an individual. In the latter case, Tipalo directly uses the entity as a class, as e.g. in the following statement mentioned in the paper:

dbp:Fastchess rdfs:subClassOf dbp:Chess
where dbp refers to http://dbpedia.org/resource/

**Comment by dorotheatsatsou** [comment]
Hi, if I may I offer my POV on this 'types' discussion.

Theoretically, Raphael is right. DBPedia ontology should provide the schema, hence all the classes that should serve as types of individuals, i.e. classes/concepts that individuals instantiate, so types should come only from within the DBPedia ontology and not the resources.

However, DBPedia ontology (although getting better and better in this subject on each newer version) still fails to fully align to this concepts-in-ontology vs. instances-in-resources conformity, since still we can find in DBPedia resources really abstract entities that should semantically comprise classes - and not in DBPedia ontology as they should.

For instance, I see in one of the LinkedTV content analysis examples that the concept "Team" is not a class in the ontology but a dbpedia resource (http://dbpedia.org/resource/Team) although "SportsTeam" - which should have been its child - is actually in the ontology (http://dbpedia.org/ontology/SportsTeam), which is, well, frankly a little bit ridiculous. Sadly, DBPedia is down for me atm to see if there's any connection between the two.

This is an issue identified in the DBPedia community as well as you can see at this Nov. 2013 DBPedia blog post: 
http://blog.dbpedia.org/2013/11/29/making-sense-out-of-the-wikipedia-categories-gsoc2013/

{+ This was one of the issues that turned us towards modeling our own ontology instead of using DBPedia. Especially looking at v3.6 which was the running version when we started defining WP4 requirements at Y1 of LTV, the coverage was far worse than in the current 3.9 version}

Hence, practically, Tomas' reasoning is valid (although more of a pain for us to map LUMO to, but we are already looking into it).

That said, looking into v3.9 (I haven't since it came out last September, last version I worked on was v3.8), I see a much better coverage, we couldn't live with the coverage of v3.6 but maybe we can do with the coverage of v3.9 (unsure, would have to compare the newest LUMO version when I'm finished against v3.9 in terms of coverage). We are fine with any decision you make, so long as this problem, identified in the blog post above, is not too big for us: "a large number of DBpedia instances is either un-typed, due to a missing mapping or a missing infobox, or has a too generic or too specialized type, due to the nature of the ontology."

**Comment by rtroncy** [comment]
Resolved, see https://lists.iais.fraunhofer.de/sympa/arc/linkedtv-wp2/2014-05/msg00001.html
